##------------##
## Containers ##
##------------##
python_container: "docker://rtpop/hedgehog-run:1.0"
r_container: "docker://rtpop/hedgehog-downstream:1.0"

##-------------##
## Directories ##
##-------------##  
src: "src" # Code directory
data_dir: "data"
output_dir: "output" # this will be a parent directory for different runs
src_dir: "src"


# list of tissues
tissue: ["Adipose_subcutaneous", "Adipose_visceral", "Adrenal_gland", "Artery_aorta",
  "Artery_coronary", "Artery_tibial", "Brain_basal_ganglia", "Brain_cerebellum", "Brain_other",
  "Breast", "Colon_sigmoid", "Colon_transverse", "Esophagus_mucosa", "Esophagus_muscularis",
  "Heart_atrial_appendage","Heart_left_ventricle", "Intestine_terminal_ileum",
  "Kidney_cortex", "Liver", "Lung", "Minor_salivary_gland", "Ovary", "Pancreas", "Pituitary",
  "Prostate", "Skin", "Spleen","Stomach", "Testis", "Thyroid", "Tibial_nerve","Uterus", "Vagina", "Whole_blood"]


## ---------- ##
## GTEX files ##
## ---------- ##
gtex_data_file: "GTEx_PANDA_net.RData"
motif_prior_file: "motif_prior.txt"
panda_edgelist_file: "panda_network_edgelist.txt"
processing_log: "process_gtex.log"


## ------------------------------ ##
## Filtering and benchmark params ##
## ------------------------------ ##
prior_only: True
bench_resolution: [0.1, 0.5, 1, 5, 10] # resolution parameter for the BRIM algorithm to calculate modularity
plot_unfiltered: False # whether to plot the unfiltered networks in the benchmark

##--------------------##
## BiHiDef parameters ##
##--------------------##
max_communities: 3 # multiplier for the maximum number of communities passed to condor
max_resolution: 5 # the maximum resolution parameter for bihidef
min_resolution: 0.001 # the minimum resolution parameter for bihidef (not used in the snakemake atm)
resolution_step: 0.001 # the step size for the resolution parameter (not used in the snakemake atm)
target_tag: "gene"
regulator_tag: "TF"

# the minimum and maximum number of genes in a community
min_genes: 10
max_genes: 200

##-------------------##
## Sambar parameters ##
##-------------------##
mut_data: "mut_ucec.txt"
esize_file: "esize.csv" # file with info about exon size
can_genes: "cancer_genes.txt" # file with cancer associated genes
gmt_file: "gene_selected_communities.gmt" # this will also be used for GO enrichment

## ------------------------ ##
## GO enrichment parameters ##
## ------------------------ ##

# file with genes to be used as background
# required only is auto_bg = False
bg_file: "annotation.txt" 
auto_bg: False # whether the background should be determined automatically from the gmt file
save_all: True # if the GO results should be saved for each community
sig_thresh: 0.05 # p value threshold for significance
statistic: "fisher" # test statistic to be used
algorithm: "classic" # topGO algorithm to be used

## ----------------------- ##
## Top mutated communities ##
## ----------------------- ##
n_top_comm: 5 # number of communities to extract

## --------------------------- ##
## Clustering community scores ##
## --------------------------- ##
binarise: True # whether to binarise scores for visualisation
log_transform: False # whether to log transform scores for visualisation

##------------------##
## Other parameters ##
##------------------##
delimiter: "," # delimiter for input & output files